### ISSUE TITLE
As far as I can tell, grunt-jasmine-nodejs *never* loads helper files without hacky workaround

### ISSUE THREAD

**Issue by grempe** [onury/grunt-jasmine-nodejs#1]
I've tried a number of combinations and I can't seem to get any config to work that will load helpers without changing the 'specNameSuffix' to '.js'.  It seems as if the code does not actually support loading a file like 'spec/SpecHelper.js'.

Here is the config I ended up with to finally get things to work:

````
    jasmine_nodejs: {
        // task specific (default) options
        options: {
            showColors: true,
            specNameSuffix: '.js', // HAD TO CHANGE THIS FROM 'spec.js' to just '.js' so helper files could be loaded!!!
            helperNameSuffix: 'helper.js', // DOES NOT APPEAR TO DO ANYTHING
            useHelpers: true  // DOES NOT APPEAR TO DO ANYTHING
        },
        secrets: {
            // target specific options
            options: {
                useHelpers: true  // DOES NOT APPEAR TO DO ANYTHING
            },
            // spec files
            specs: [
                "spec/**"
            ],
            helpers: [
                "spec/**"  // DOES NOT APPEAR TO DO ANYTHING
            ]
        }
    }
  });

````

Thanks.

**Comment by onury** [comment]
Thanks for the heads-up. I've just updated to version 0.4.0 that fixes this and includes some additional tweaks. Please let me know if this works for you.

**Comment by grempe** [comment]
Works great now.  Thanks for the quick fix and release.

Glenn

**Comment by onury** [comment]
Thanks Glenn. Glad to hear that.
