### ISSUE TITLE
When using Jasmine 2.3.0, no tasks after the first `grunt-jasmine-nodejs` task run

### ISSUE THREAD

**Issue by sethkinast** [onury/grunt-jasmine-nodejs#15]
I am seeing new behavior with Jasmine 2.3.0 (just released). I can no longer run Grunt tasks after `grunt-jasmine-nodejs` runs.

Here is the correct behavior, using Jasmine 2.2.1. Two Grunt tasks run.

```
$ npm ls jasmine
dustjs-linkedin@2.7.0 /Users/skinast/code/dustjs
└─┬ grunt-jasmine-nodejs@1.0.2
  └── jasmine@2.2.1

$ grunt jasmine_nodejs:dustc jasmine_nodejs:cjs
Running "jasmine_nodejs:dustc" (jasmine_nodejs) task
Executing specs...

∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙

11 suites, 15 specs, 27 asserts, 0 failures
Finished in 2.926 seconds

>> Successful!

Running "jasmine_nodejs:cjs" (jasmine_nodejs) task
Executing specs...

∙∙∙∙∙∙

1 suite, 6 specs, 7 asserts, 0 failures
Finished in 0.013 seconds

>> Successful!

Done, without errors.
```

And here is the output from a fresh npm install, now that Jasmine 2.3.0 is being installed. **Notice that the second task is not run.** In fact, no Grunt tasks after the first `jasmine_nodejs` task get run, even if they are not `jasmine_nodejs` tasks.

```
 npm ls jasmine
dustjs-linkedin@2.7.0 /Users/skinast/code/dustjs
└─┬ grunt-jasmine-nodejs@1.0.2
  └── jasmine@2.3.0

skinast-mn1:dustjs skinast$ grunt jasmine_nodejs:dustc jasmine_nodejs:cjs
Running "jasmine_nodejs:dustc" (jasmine_nodejs) task
Executing specs...

∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙

11 suites, 15 specs, 27 asserts, 0 failures
Finished in 2.893 seconds

>> Successful!
```

**Comment by sethkinast** [comment]
Also note that `Done, without errors` does not appear in the second output.

**Comment by sethkinast** [comment]
I should also add that the same behavior occurs if I use the latest version of `grunt-jasmine-nodejs` (but my project is still using `1.0.2`.

**Comment by kylezeeuwen** [comment]
Having the same issue

**Comment by onury** [comment]
Thanks for reporting.
Pls try the latest version (1.4.0) and let me know if this is resolved for you.

**Comment by sethkinast** [comment]
Thanks!

I confirm that the problem I was seeing where ensuing test suites are not run is fixed.

However the new `stopOnFailure` option does not seem to be respected. A failing test suite always aborts.

```
$ grunt jasmine_nodejs
Running "jasmine_nodejs:cjs" (jasmine_nodejs) task

>> Executing 8 defined specs...
>> Done!


Failed Specs:

1) test

Summary:

Suites:  1 of 1
Specs:   8 of 8
Expects: 9 (2 failures)
Finished in 0.020 seconds

Warning: Task "jasmine_nodejs:cjs" failed. Use --force to continue.
```

**Comment by onury** [comment]
Thanks for your feedback.

As stated in the docs, `stopOnFailure` is only for expectation failures. 
This does not watch for suite failures (such as errors thrown in `afterAll`, etc..).

I see that in your example, you've set `stopOnFailure` to `false`. And you've got all 2 failures; which is the expected behaviour. If you set it to `true`, the runner will stop on the first expect-failure and in the summary, you'll always see 1 failure.

A side-note: Regardless of the `stopOnFailure` option; if you're running more than 1 task target, grunt will also abort when a task/target fails, and will not run the next.

**Comment by sethkinast** [comment]
Got it. Sounds good!

On Fri, May 1, 2015 at 10:45 AM, Onur Yıldırım <notifications@github.com>
wrote:

> Closed #15 <https://github.com/onury/grunt-jasmine-nodejs/issues/15>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onury/grunt-jasmine-nodejs/issues/15#event-295080030>.
>



-- 
Seth Kinast
http://sethkinast.com/

**Comment by onury** [comment]
Improved definition of `stopOnFailure` option in [readme](https://github.com/onury/grunt-jasmine-nodejs#stoponfailure) file.

**Comment by andresmanelli** [comment]
Sorry for reviving this old issue but I'm facing the same problem with: 

```json
"grunt-jasmine-nodejs": "~1.5.2",
"jasmine-core": "^2.4.1"
```

Any comments?
