### ISSUE TITLE
[documentation] `useHelpers` actually defaults to false

### ISSUE THREAD

**Issue by sethkinast** [onury/grunt-jasmine-nodejs#16]
The documentation says that `useHelpers` should default to true.

However it [actually defaults to false](https://github.com/onury/grunt-jasmine-nodejs/blob/master/tasks/jasmine.task.js#L62).

The option works fine once it is set to true.

**Comment by onury** [comment]
Thanks. Will fix this in the next release.

**Comment by onury** [comment]
Fixed.
