### ISSUE TITLE
Running suite with `fdescribe` and `fit` specs should not display skipped specs

### ISSUE THREAD

**Issue by fiznool** [onury/grunt-jasmine-nodejs#17]
When running with the console reporter at verbosity level 3, if you use Jasmine's focussed suite/spec feature (`fdescribe`/`fit`), the console reporter still displays every test result.

IMO it should not display the results of the specs that were skipped. In my case, I have over 1600 specs, and so running a focussed test run on (say) 10 tests should not display the results of the remaining 1590, which I don't care about.

**Comment by onury** [comment]
Ok. I'll take care of this with the next patch or release.

**Comment by fiznool** [comment]
Bump... any ideas when this might be fixed?

I'm happy to help with a PR but I'm not really sure where to start.

**Comment by onury** [comment]
Hi. I think I'll have time to fix it next week if not earlier.

**Comment by onury** [comment]
Expanded `verbosity` levels (0 to 4) of console reporter. (See [docs](https://github.com/onury/grunt-jasmine-nodejs#reporters)). You should now set this to `3` to get a list report without the disabled specs.

Closing this now. Pls let me know or re-open if smth is wrong.
