### ISSUE TITLE
Hook into code coverage tools?

### ISSUE THREAD

**Issue by noahsw** [onury/grunt-jasmine-nodejs#18]
First off - great tool! I'd been looking for something like this for a while.

I'm trying to use this to build code coverage reports out of jasmine. Any ideas how to hook into something like istanbul?

**Comment by onury** [comment]
Thanks @noahsw.  
Too busy recently but will definitely look into it.

**Comment by mikedon** [comment]
I wouldn't mind picking up this request.  I need it for one of my projects.  Have you already started writing something?

**Comment by 4kochi** [comment]
Actually you can use Istanbul directly with jasmine. Just add "jasmine" and "istanbul" as dev dependencies and add a jasmine.json confit file. Here is an example of a shell command:

node node_modules/istanbul/lib/cli.js cover --dir build/reports/coverage node_modules/jasmine/bin/jasmine.js -- JASMINE_CONFIG_PATH=test/jasmine.json

You also use a grunt/gulp plugin to run the shell command from there. We use this to open the browser with the code coverage report after the code coverage has run.

**Comment by mikedon** [comment]
That sounds like your removing the use of this plugin entirely.  I still want to use this plugin to encapsulate the unit testing configuration but I just think this plugin should also support code coverage and threshold checking.

**Comment by 4kochi** [comment]
Well, I would say this module is just a grunt task wrapper for jasmine-node. So it's not the responsibility of this module to handle the code coverage. I agree that jasmine-node itself should take part on that case. But anyway, i am not the maintainer of this module so let's see how @onury will handle this request. 

In our case, we are using this plugin to run our tests, and we use Istanbul to get our code coverage. There is even a grunt plugin for Istanbul, but we found the shell command more handy.

**Comment by onury** [comment]
Well, I'd agree with @4kochi.
Also, keeping this as simple as I can so I can maintain better... :bowtie:
