### ISSUE TITLE
No README data warning when installing other packages w/ v0.4.0

### ISSUE THREAD

**Issue by grempe** [onury/grunt-jasmine-nodejs#2]
I am seeing the following warning when trying to install other NPM packages.

````
$ npm install ANOTHER_NPM_PACKAGE --save-dev
npm WARN package.json grunt-jasmine-nodejs@0.4.0 No README data
````

Thoughts?

**Comment by onury** [comment]
I've tried to reproduce this but didn't get that warning. Besides, the repo has a [README.md](https://github.com/onury/grunt-jasmine-nodejs/blob/master/README.md) file. 

Which version of NPM are you using? Could you run an update and try with a new/empty project?

**Comment by grempe** [comment]
````
$ npm --version
2.6.1

$ npm install -g npm@latest
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.6.1 /usr/local/lib/node_modules/npm
````

There are a bunch of search results for people getting similar warnings.  I have not yet dug into the reasons or fixes yet though (and won't unless I see this again).

https://duckduckgo.com/?q=npm+No+README+data&ia=qa

When I blew away 'node_modules' in the project dir and did an 'npm install' I didn't see the warning again.  So I'll close this if no one else is seeing the problem.

Thanks for taking a look.

**Comment by onury** [comment]
No problem @grempe. I'm aware of that warning but it occurs if you don't have a readme file or if your readme file is empty. We just don't have that problem. Thanks for your input though.
