### ISSUE TITLE
Don't use process.stdout.clearLine if the output is not a tty

### ISSUE THREAD

**Issue by briangreenery** [onury/grunt-jasmine-nodejs#20]
It looks like `process.stdout.clearLine` is used to format output for disabled tests. However, this will cause the tests to fail when the test output is piped to a file because `clearLine` is undefined when `process.stdout` is not a tty.

Like, running `grunt jasmine_nodejs` at an interactive terminal will succeed, but `grunt jasmine_nodejs > out` will fail if you have any disabled tests.

This is an issue on node `0.12.6`. I don't think this was an issue on `0.10.38`, but I'm not sure.

**Comment by davidparsson** [comment]
This is an issue for me as well. This fix will result in a lot of blank lines in the test report. It's not ideal, but it's better than a lot of exceptions.

**Comment by onury** [comment]
Thanks. I'll look into this to see if there's a better workaround.

**Comment by onury** [comment]
This is fixed in [Jasmine Console Reporter](https://github.com/onury/jasmine-console-reporter).
