### ISSUE TITLE
Running console reporter with verbosity `3` should not display disabled suite names

### ISSUE THREAD

**Issue by fiznool** [onury/grunt-jasmine-nodejs#24]
If you have a lot of tests, and you are only running one or two specs with `fit` / `fdescribe`, running the default reporter at verbosity level 3 displays the enabled tests but also prints the names of all the disabled suites afterwards. This causes issues when you are debugging by inserting console.log statements in your focussed specs, as the output you are interested in is often lost.

It would therefore be nice if the disabled suite names could be hidden in this mode.

**Comment by fiznool** [comment]
For an example of this in action, check out the karma-mocha-reporter.

With the option `ignoreSkipped` set, you get the following (example) output:

```
Start:
  Controller: TaskRunLogItemCtrl
    Set Data
      ✔ should set data for a trigger which received items (legacy mode)
      ✔ should set data for a trigger which received an item
      ✔ should set data for a filtered trigger
      ✔ should set data for a successful task run
      ✔ should set data for a filtered task run
      ✔ should set data for a filtered task run (legacy schema)
      ✔ should set data for a successful wait `for` task
      ✔ should set data for a successful wait `until` task
      ✔ should set data for an error
    Toggle Extra Info
      ✔ should toggle the extra info pane

Finished in 0.346 secs / 0.065 secs

SUMMARY:
✔ 10 tests completed
ℹ 919 tests skipped

Done, without errors.
```

Notice the skipped tests aren't displayed.

**Comment by onury** [comment]
Sorry. This package is [deprecated](https://github.com/onury/grunt-jasmine-nodejs/#warning-deprecated). Still maintaining [Jasmine Console Reporter](https://github.com/onury/jasmine-console-reporter).
