### ISSUE TITLE
Failed specs not showing for me 

### ISSUE THREAD

**Issue by mageddo** [onury/grunt-jasmine-nodejs#28]
When a test throws a exception, it does not show a stack trace for me, as follows an example of my output when run grunt test. Can you help me?

	 10) deleteBookmarkPermanently
	queryBulk iniciando...
	queryBulk begin finalizado
	deleteBookmarkPermanently sucesso >>  null [ { rows: [], insertId: undefined, count: 1 },
	  { rows: [], insertId: undefined, count: 2 } ]
	      ✔ sucesso

	11) Snooze
	queryBulk callback finalizada
	queryBulk commit finalizado
	fechando conexão..
	queryBulk finalizado
	   ✔ disparando testes...

	12) TagModel
	before test....
	inserindo...
	   ✖ insertTag sucesso (1 failure)

	   13) searchTagsByName
	queryAuto
	fechando conexão..
	searchTagsByName sucesso >>  null []
	Fatal error: 0 != 0

My configuration is:

	jasmine_nodejs: { // jshint ignore:line
		options: {
			specNameSuffix: "Test.js", // also accepts an array 
			helperNameSuffix: "Helper.js",
			useHelpers: true,
			stopOnFailure: false,
			reporters: {
				console: {
					colors: true,
					cleanStack: 3, // (0|false)|(1|true)|2|3 
					verbosity: 4, // (0|false)|1|2|3|(4|true) 
					listStyle: "indent", // "flat"|"indent" 
					activity: true
				},
				terminal: {
					color: true,
					showStack: true,
					verbosity: 2
				}
			}
		},
		testing: {
			specs: [
				'<%= meta.test %>/**'
			],
			helpers: [
				'<%= meta.test %>/helper/**'
			]
		}
	},
       ....
       grunt.registerTask('test', ['jasmine_nodejs']);

the test

	describe('TagModel', function() {

		it('insertTag sucesso', function(done){
			console.log('before test....');
			throw "a error";
			
		});
       ........

**Comment by onury** [comment]
Pls try setting the `cleanStack` option to `0` or `false`.

**Comment by mageddo** [comment]
Yep I've tried it, not works,

I have discovered that the main problem is on `stopOnFailure` and `expect` assertion **only when used on `async` tests**, consider the test bellow  to reply the follow question:

> Okay, if I remove `expect(items.length).not.toEqual(0);`  everything will work fine but how `expect(error).toEqual(null);` was tested and receive `false` then the test can not keep running, right? When `stopOnFailure: false` the ideia is not stop this test and keep running the others tests? Anyway can you help me with this `async` question? Thank you very much
 

# Async test 
	it('async callback test', function(done){

		setTimeout(function(){
			var error = 'a error', items = null;
			expect(error).toEqual(null);
			console.log('hey, the test has failed but I am called!?');
			expect(items.length).not.toEqual(0);
			done();
		}, 1000);

	});


If I set `stopOnFailure: true` even `cleanStack:false|0` the output is:

	Running "jasmine_nodejs:testing" (jasmine_nodejs) task

	>> Executing 1 defined specs...

	Test Suites & Specs:

	1) hello world
	Fatal error: Error


Now, if I set `stopOnFailure: false` even `cleanStack:false|0` the output is:

	Running "jasmine_nodejs:testing" (jasmine_nodejs) task

	>> Executing 1 defined specs...

	Test Suites & Specs:

	1) hello world
	hey, the test has failed but I am called!?
	Fatal error: Cannot read property 'length' of null


# Sync Test
Here everything works fine

	describe('hello world', function(){
		it('async callback test', function(done){

			// setTimeout(function(){
				var error = 'a error', items = null;
				expect(error).toEqual(null);
				console.log('hey, the test has failed but I am called!?');
				expect(items.length).not.toEqual(0);
				done();
			// }, 1000);

		});

If I set `stopOnFailure: true` even `cleanStack:false|0` the output is:

	Running "jasmine_nodejs:testing" (jasmine_nodejs) task

	>> Executing 1 defined specs...

	Test Suites & Specs:

	1) hello world
		 ✖ async callback test (1 failure)

	>> Done!


	Failed Specs:

	1) hello world : async callback test
		 Error: Expected 'a error' to equal null.
		     at stack /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1577:17
		     at buildExpectationResult /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1547:14
		     at Spec.Env.expectationResultFactory /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:638:18
		     at Spec.addExpectationResult /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:330:34
		     at Expectation.addExpectationResult /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:588:21
		     at Expectation.toEqual /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1501:12
		     at Object.<anonymous> /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/src/test/test/TmpTest.js:18:19
		     at attemptAsync /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1916:24
		     at QueueRunner.run /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1871:9
		     at QueueRunner.execute /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1859:10

	Summary:

	Suites:  1 of 1
	Specs:   1 of 1
	Expects: 1 (1 failure)
	Finished in 0.015 seconds



if I set `stopOnFailure: false` even `cleanStack:false|0` the output is:

	Running "jasmine_nodejs:testing" (jasmine_nodejs) task

	>> Executing 1 defined specs...

	Test Suites & Specs:

	1) hello world
	hey, the test has failed but I am called!?
		 ✖ async callback test (2 failures)

	>> Done!


	Failed Specs:

	1) hello world : async callback test
		 Error: Expected 'a error' to equal null.
		     at stack /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1577:17
		     at buildExpectationResult /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1547:14
		     at Spec.Env.expectationResultFactory /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:638:18
		     at Spec.addExpectationResult /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:330:34
		     at Expectation.addExpectationResult /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:588:21
		     at Expectation.toEqual /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1501:12
		     at Object.<anonymous> /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/src/test/test/TmpTest.js:18:19
		     at attemptAsync /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1916:24
		     at QueueRunner.run /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1871:9
		     at QueueRunner.execute /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1859:10
		 TypeError: Cannot read property 'length' of null
		     at Object.<anonymous> /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/src/test/test/TmpTest.js:20:17
		     at attemptAsync /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1916:24
		     at QueueRunner.run /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1871:9
		     at QueueRunner.execute /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1859:10
		     at Spec.Env.queueRunnerFactory /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:697:35
		     at Spec.execute /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:359:10
		     at Object.fn /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2479:37
		     at attemptAsync /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1916:24
		     at QueueRunner.run /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1871:9
		     at QueueRunner.execute /home/system/Dropbox/dev/projects/mageddo-web-3.0/mageddo-api/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1859:10

	Summary:

	Suites:  1 of 1
	Specs:   1 of 1
	Expects: 2 (2 failures)
	Finished in 0.017 seconds

**Comment by onury** [comment]
First, your sync example is still async since you've defined the `done` argument. 

Second, `stopOnFailure` is only intended for expectation failures, not fatal errors. (`items.length` is a fatal error bec. `items` is `null`). Fatal errors will stop execution immediately (they're **fatal**). They occur when you have a fault within the spec/suite code. That's not an expectation failure, so setting `stopOnFailure` to `true` will not help here.

Noted in [docs](https://github.com/onury/grunt-jasmine-nodejs#stoponfailure):
> stopOnFailure: Specifies whether to stop running further tests, on first expectation-failure. This can be useful if you want to debug your failed specs one by one. Note: Regardless of this option; the runner will still stop on suite failures (such as errors thrown in afterAll, etc) and as normal, Grunt will abort when a task/target fails.

Your spec example **without `setTimeout`** works fine bec. when the code is executed, it's properly caught for errors by Jasmine and before the fatal error line with `items.length` is executed, Jasmine stops at the first exception failure (`expect(error).toEqual(null)`).

But the spec **with `setTimeout`** is sent to the event queue to be executed on the nearest timer tick. Then the whole code within the `setTimeout` function block is executed, out of Jasmine's control. It is not (cannot be) caught by Jasmine, so the line with fatal error gets executed.

```js
try {
    setTimeout(function () {
        throwError(); // not defined
    }, 1000);
}
catch (error) {
    console.log('this will NOT log');
}
```
In the example above, the error will not be caught and will throw `Uncaught ReferenceError: throwError is not defined` after 1000 ms.

**Comment by mageddo** [comment]
Ya, thank you. From the `jasmine` documentation the problem is that I need to execute **async** commands on `beforeEach`, `jasmine` not catch `async` exceptions like `mocha`, but I do not have tested it
  
    describe("Asynchronous specs", function() {
        var value;
        beforeEach(function(done) {
          setTimeout(function() {
            value = 0;
            done();
          }, 1);
        });
        
        it("should support async execution of test preparation and expectations", function(done) {
          value++;
          expect(value).toBeGreaterThan(0);
          done();
        });
    });
