### ISSUE TITLE
Extract console reporter as separate node package

### ISSUE THREAD

**Issue by msrose** [onury/grunt-jasmine-nodejs#29]
The default reporter in `grunt-jasmine-nodejs/tasks/lib/console.reporter.js` is by far my favourite jasmine reporter. Looks great on all platforms. Would you consider maintaining it as a separate npm package so it can be used more easily with non-grunt projects?

**Comment by onury** [comment]
Ok. I'll do that soon. Thanks.

**Comment by onury** [comment]
Here you go: https://github.com/onury/jasmine-console-reporter
