### ISSUE TITLE
Package Doesn't Work With Node <= 0.12

### ISSUE THREAD

**Issue by destroyerofbuilds** [onury/grunt-jasmine-nodejs#32]
As of 5a39c20261136e5d2d447023e51d13cd096b7e02 this package now uses a native ES6 function `endsWith`. 

That function is not available in Node 0.10 and 0.12, both of which are supported versions of Node (0.12 is an LTS version).

Yet the `package.json` file says this package is compatible with Node >= 0.8. 

Several of my builds still test packages against Node 0.10 and 0.12, causing this minor change to break those builds.

**Comment by onury** [comment]
Thanks for reporting. 
Pls try v1.5.1 and let me know.

**Comment by destroyerofbuilds** [comment]
Thanks @onury!

So I jumped into a project with the following environment:

```bash
node --version
v0.12.10

npm --version
3.7.5
```

I first installed v1.5.0:

```bash
npm install grunt-jasmine-nodejs@1.5.0
```

And ran my build:

```
(~) grunt jasmine_nodejs
Running "jasmine_nodejs:test" (jasmine_nodejs) task

>> Executing 0 defined specs...

Test Suites & Specs:

>> Done!
```

No tests found because of the silent failure around `endsWith`.

I then updated to v1.5.1:

```
npm install grunt-jasmine-nodejs@1.5.1
```

It now finds my placeholder spec file:

```
grunt jasmine_nodejs
Running "jasmine_nodejs:test" (jasmine_nodejs) task

>> Executing 1 defined specs...

Test Suites & Specs:

1) module
   ✔ should have tests

>> Done!
```

**Comment by onury** [comment]
Good to know it works for you now.
Strange that it was a silent failure, though.
cheers.
