### ISSUE TITLE
Jasmine createSpyObj warning is not displayed

### ISSUE THREAD

**Issue by brentsnook** [onury/grunt-jasmine-nodejs#33]
Hi,

We have noticed that warnings from Jasmine don't seem to be appearing, specifically the one related to not supplying a spy method list to jasmine.createSpyObj.

If I run the specs with the jasmine node package:
```
> /usr/local/bin/jasmine
Started
FF

Failures:
1) jasmine.createSpyObj handles an empty spy list
  Message:
    createSpyObj requires a non-empty array of method names to create spies for thrown
  Stack:
```

But when I run jasmine as part of the grunt build:

```
> grunt
Running "jasmine_nodejs:test" (jasmine_nodejs) task

>> Executing 2 defined specs...

Test Suites & Specs:

1) jasmine.createSpyObj
   ✖ handles an empty spy list (1 failure)
   ✖ handles a missing spy list (1 failure)

>> Done!

Failed Specs:

1) jasmine.createSpyObj : handles an empty spy list

2) jasmine.createSpyObj : handles a missing spy list

Summary:

Suites:  1 of 1
Specs:   2 of 2
Expects: 2 (2 failures)
Finished in 0.007 seconds

Warning: Task "jasmine_nodejs:test" failed. Use --force to continue.
Error: Task "jasmine_nodejs:test" failed.
  at Task.<anonymous> (/.../jasmine-issue/node_modules/grunt/lib/util/task.js:198:15)
  at [object Object]._onTimeout (/.../jasmine-issue/node_modules/grunt/lib/util/task.js:234:33)
  at Timer.listOnTimeout (timers.js:92:15)

Aborted due to warnings.
```

How can I ensure that this warning shows up in the Grunt output? Am I missing some configuration or is this a bug?

[Gruntfile.js.txt](https://github.com/onury/grunt-jasmine-nodejs/files/254489/Gruntfile.js.txt)
[brokenSpec.js.txt](https://github.com/onury/grunt-jasmine-nodejs/files/254490/brokenSpec.js.txt)
grunt: v1.0.1
grunt-jasmine-nodejs: v1.5.2

**Comment by onury** [comment]
Thanks for reporting @brentsnook.
This is actually a bug with [jasmine-console-reporter](https://github.com/onury/jasmine-console-reporter).

The reason is that the failed spec has no stack but an error message. This is almost never the case but turns out it happens.

I'm fixing it now. Both repo's will be updated shortly.

I'd appreciate if you could open this issue on the reporter's [repo](https://github.com/onury/jasmine-console-reporter).

**Comment by onury** [comment]
This is fixed in `grunt-jasmine-nodejs` v1.5.3 (and `jasmine-console-reporter` v1.2.6)

**Comment by brentsnook** [comment]
Cheers, would you still like me to open the issue on the other repo?

**Comment by onury** [comment]
No, I meant this issue belongs there. No need, though. Thanks.
