### ISSUE TITLE
Failing with TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by sanmahad** [onury/grunt-jasmine-nodejs#34]
Hi,

I have installed the 
 "grunt": "^0.4.5",
"grunt-jasmine-nodejs": "^1.5.2"
npm - 2.11.3
node - 0.12.7

I have the jasmine_nodejs grunt task configured to run my node tests. After I ran the tests with grunt jasmine_nodejs, the tests are fine but at the end it is throwing this error message - 

C:\TestWebUI\Query\node_modules\grunt\lib\grunt\fail.js:30
  var msg = String(e.message || e);
                    ^
TypeError: Cannot read property 'message' of undefined
    at writeln (C:\TestWebUI\Query\node_modules\grunt\lib\grunt\fail.js:30:21)
    at Object.fail.fatal (C:\TestWebUI\Query\node_modules\grunt\lib\grunt\fail.js:55:3)
    at process._taskFatalHandler_ (C:\TestWebUI\Query\node_modules\grunt-jasmine-nodejs\tasks\jasmine.task.js:249:19)
    at process.emit (events.js:129:20)
    at process._fatalException (node.js:236:26)

I'm unable to run any subsequent tasks since this task is failing. Please help.

Thanks
Sandeep

**Comment by onury** [comment]
Thanks @sanmahad.
I cannot reproduce this but it seems, in your case; Grunt does not pass an error object even though the task fails. This is now handled in v1.5.3. Pls update and let me know if it works for you.

**Comment by sanmahad** [comment]
Hi,

I was getting this error when my tests were throwing back the errors. When my tests dont throw error then this issue doesn't occur. This issue can be closed.

Thanks
Sandeep
