### ISSUE TITLE
You can't require same file multiple times in different specs

### ISSUE THREAD

**Issue by jcubic** [onury/grunt-jasmine-nodejs#35]
I have 3 specs that require same file (it's dependency on each module I'm testing):

```javascript
$.platform = $.platform || {};
console.log($.platform.formSupport);
require('../runtime/platform/js/modules/platform.formSupport.js');
console.log($.platform.formSupport);
```
and only the second console display the correct object the rest display undefined.

**Comment by onury** [comment]
Are you sure this is related with this module or jasmine itself?
Can you try running your specs with `/usr/local/bin/jasmine` and check if you see the same behaviour.

Also you could also try `delete require.cache[file]`

**Comment by jcubic** [comment]
I've used `delete require.cache[file]` to unload the module and it work.
