### ISSUE TITLE
Code Coverage required to be built in with this tool

### ISSUE THREAD

**Issue by sanmahad** [onury/grunt-jasmine-nodejs#37]
Hi,

I'm surprised why there is no code coverage for this tool. grunt-jasmine-node has code coverage support and I believe the same support should be there for this tool as well.

We can however get the code coverage with istanbul command line, but it will again run all the tests which will be time consuming.

I strongly recommend to have the code coverage for this tool.

Thanks
Sandeep

**Comment by onury** [comment]
Sorry. This plugin is [deprecated](https://github.com/onury/grunt-jasmine-nodejs/#warning-deprecated).
