### ISSUE TITLE
 afterAll() cleanup is not called if an error occured within a spec

### ISSUE THREAD

**Issue by mgcam** [onury/grunt-jasmine-nodejs#38]
grunt-jasmine-nodejs ^1.5.2
afterAll() cleanup is not called if an error occured within a spec
Should this issue be raised in https://github.com/mhevery/jasmine-node as well or instead?

**Comment by onury** [comment]
This plugin has no dependency on `jasmine-node`. It uses the official `jasmine-core` internally.

I cannot reproduce this. `afterAll` is fired in my tests. 
Pls update `grunt-jasmine-nodejs` to the latest version and re-try.

You can also try running your tests directly with jasmine (v2.4.x) without this plugin and see what happens.

**Comment by mgcam** [comment]
Hi Onur

On 23/05/2016 12:34, Onur Yıldırım wrote:
> I cannot reproduce this. |afterAll| is fired in my tests.
> Pls update |grunt-jasmine-nodejs| to the latest version and re-try.
Thank you very much for your suggestion. Works with v 1.5.3. Marina



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
