### ISSUE TITLE
Confusing helper path declaration

### ISSUE THREAD

**Issue by mrackwitz** [onury/grunt-jasmine-nodejs#39]
When I specify a full path in `helpers`, it isn't just loaded. The suffix still has to match the `helperNameSuffix` which is by default `helper.js`. That is not very intuitive, especially if you don't know about the latter option at all. It mismatches with Grunt's general concept of [configuring files](http://gruntjs.com/configuring-tasks#files). It would be much more intuitive if the current default behavior wouldn't be built-in and demonstrated instead in the README utilizing this concept.
Beside that `helpers` can't be declared in the global `options` as far as I can see. I'd expect that I can declare there a set of files, which is shared across all my spec targets.

**Comment by onury** [comment]
Thanks for the input.
With v1.6.0 —
- `specNameSuffix` and `helperNameSuffix` options are deprecated. Use glob notation when defining spec and helper files for any task target.
- Added `helpers:Array` option which defines global helpers available to all task targets.
- Full spec file-paths are respected (no need to match suffixes).

**Comment by onury** [comment]
Closing this. Please re-open if you need to.
