### ISSUE TITLE
Consider integrating jasmine-reporters

### ISSUE THREAD

**Issue by fiznool** [onury/grunt-jasmine-nodejs#4]
https://github.com/larrymyers/jasmine-reporters

**Comment by 4kochi** [comment]
That would be great. We want to switch to this module be we need the JUnit reporter.

**Comment by fiznool** [comment]
@onury I can have a stab at adding this in and send a PR if you like. I was thinking of a new option:

```
reporters: {
  junit: {
    savePath: '..',
    consolidateAll: false
  }
}
```

Each `reporters` object defines a format where the reporter name is the key, followed by the reporter-specific options as an object. This could be passed through to create a new reporter. It could then be added with `jasmine.addReporter()`.

**Comment by onury** [comment]
Thanks. This should definitely be implemented.
@fiznool It'd be great. Let me have a look at this first.

**Comment by onury** [comment]
Ok. I had to make some other modifications to add support for this. 

@fiznool I've took your suggestion for the `reporters` object. And a `customReporters` array can be defined for external reporters. Thanks for your input.

Lots of revisions done, various features added..  I think this deserves bumping up the version to **1.0.0**
Please read the updated documentation (for the new features and some deprecations).

@4kochi I hope this will work for you. I'd be glad to hear some feedback from you, too; so we can close this if everything is ok.

cheers

**Comment by fiznool** [comment]
Looks fantastic!

If you are bumping to 1.0.0, I think you could remove the deprecated options completely for the old console reporter configuration, and instead mention as a breaking change in the changelog.

**Comment by onury** [comment]
Thanks @fiznool 
Well, this was a quick release so I kept that couple of lines for now.
