### ISSUE TITLE
Using filters after setup in a registered task

### ISSUE THREAD

**Issue by peteringraham** [onury/grunt-jasmine-nodejs#43]
This is more a "question" than an "issue", although it might be an issue if there's no way around it...  maybe I'm missing something really obvious here, not sure.  How do you pass the filter flag to a registered task?

Basically:
`grunt jasmine_nodejs`
Runs all tests, works as expected.
`grunt jasmine_nodejs:unit`
Runs the test setup specified in the "unit" section of var jasmineNodejs that is passed to `grunt.initConfig` .  Works as expected.
`grunt jasmine_nodejs:unit --filter=foo`
Runs the foo spec.  Works as expected.

```
grunt.loadNpmTasks('grunt-jasmine-nodejs');
grunt.registerTask('test', 'Runs unit tests', function runUnitTests(testRegex) {
        grunt.task.run('jasmine_nodejs:unit:filter=' + testRegex);
    });
```
...this, however, does not work.  It will run the equivalent of `grunt jasmine_nodejs:unit` just fine, but the filter arg is seemingly dropped on the floor.  Nor does an array (it interprets the later args as different tasks, and there's no "filter" task - see [Grunt's parsing logic](https://github.com/gruntjs/grunt/blob/master/lib/util/task.js#L107).  "Filter" seems to get entirely eaten.  Nor does `:--filter=` .  Nor does hard-coding a testRegex for filter.  (And a space gets interpreted as a really long nonexistent task that gets grunt upset.)

Am I missing something obvious here?  How do I make it so that I can run `grunt test:nameOfSpec` ?   (There's a little bit of other logic I'm omitting here.)

**Comment by onury** [comment]
This is not an issue with this plugin.
This is a question for Grunt task runner.
Please ask this on StackOverflow or Grunt-related platforms.
