### ISSUE TITLE
no task runs after the tests

### ISSUE THREAD

**Issue by cjorji** [onury/grunt-jasmine-nodejs#46]
once the tests are done, no other tasks after them, for example:

`grunt.registerTask('default', 'placeholder0', function(){
		grunt.task.run(['task0', 'jasmine_nodejs', 'task1', 'task2', 'task3']);
	});`

task0 runs, but 1,2 and 3 don't run at all

tanks in advance!

**Comment by onury** [comment]
Do your Jasmine tests fail? If so, it's normal that Grunt does not run remaining tasks. You can try `--force` option though.
