### ISSUE TITLE
Can't get junit reporter to output anything

### ISSUE THREAD

**Issue by testpossessed** [onury/grunt-jasmine-nodejs#5]
I am running on Windows, which hopefully shouldn't make any difference, but I cannot get the junit reporter to generate any output.  It runs the tests fine and they all pass but only the console reporter is generating output.  Am I missing something.

I have updated both grunt-jasmine-nodejs and jasmine-reporters packages but still no output.

I originally configured the task without a reporters block to get it running my tests, and it worked fine with just the default console reporter.  Then I added in the reporters block, but see no difference at all.

This is my current task configuration

```javascript
 jasmine_nodejs: {
            options: {
                specNameSuffix: 'Spec.js',
                useHelpers: false,
                reporters: {
                    console: {
                        colors: true,
                        cleanStack: true,
                        verbose: true
                    },
                    junit: {
                        savePath: './Results'
                    }
                }
            },
            all: {
                specs: './specs/unit/server/**'
            }
        },
```
What am I doing wrong?

**Comment by 4kochi** [comment]
There is a bug in the code. I have the same problem. The reporters object from the config is not set when the task options are loaded.

```js
var options = task.options({
            specNameSuffix: 'spec.js', // string or array
            helperNameSuffix: 'helper.js',
            useHelpers: false,
            showColors: true, // DEPRECATED
            verboseReport: true, // DEPRECATED
            reporters: {} // reporters is empty object
            // , customReporters: []
        });
```

should be: 

```js
var options = task.options({
            specNameSuffix: 'spec.js', // string or array
            helperNameSuffix: 'helper.js',
            useHelpers: false,
            showColors: true, // DEPRECATED
            verboseReport: true, // DEPRECATED
            reporters: conf.reporters || {} // use reporters from config
            // , customReporters: []
        });
```

**Comment by testpossessed** [comment]
Well spotted, I had a look at my local code and didn't see that.  It seems that despite running 
``` npm update grunt-jasmine-nodejs
```
I still had v0.4.* installed.  Uninstalling and re-installing with npm got me the latest code so I can fix it locally

Thanks

**Comment by onury** [comment]
@4kochi I get the expected options without that tweak. I'm running Grunt v0.4.5. 

Inside a task definition `this.options({...})` will set the defaults (with task level options) for the target and extend it with target level options. See [doc here](http://gruntjs.com/api/inside-tasks#this.options).

@testpossessed, @4kochi Which Grunt version are you running?
Just do `grunt --version` and paste it here please.

I'll still patch this if this is a version issue.

**Comment by testpossessed** [comment]
grunt --version produced the following in my case
grunt-cli v0.1.13
grunt v0.4.5

After the re-install of the package I updated my local file as suggested by 4kochi and all is working fine.

**Comment by 4kochi** [comment]
ah ok, was my error. Forget the options object. This works fine:

```js
asmine_nodejs: {
            options: {
                specNameSuffix: 'spec.js', // also accepts an array
                reporters: {
                    console: {
                        colors: true,
                        cleanStack: true,
                        verbose: false
                    }
                }
            },
            all: {
                specs: ['test/**']
            },
            ci: {
                specs: ['test/**'],
                options: {
                    reporters: {
                        junit: {
                            savePath: '<%= src.reports %>/jasmine/'
                        }
                    }
                }
            }
        }
```

**Comment by onury** [comment]
So @testpossessed can you please re-check your project/config without the tweak @4kochi suggested. It should be working without that. Feel free to re-open this issue if you need help or anything is wrong.

One side-note: just remember that the target-level `reporters` object will override the task-level `reporters` all together. They will not be merged.

**Comment by testpossessed** [comment]
It works fine without the tweak.  My issue was clearly the npm update not getting the latest version
