### ISSUE TITLE
Symbols ('•', ' ✕ ', '✓') are not printed in Windows

### ISSUE THREAD

**Issue by 4kochi** [onury/grunt-jasmine-nodejs#6]
Since the windows console is really weird it has problems with the symbols you print. I had the same problems, also with colors.

I use now to the following two modules for colors and symbols. Works fine cross platform.

https://github.com/sindresorhus/log-symbols
https://github.com/sindresorhus/chalk

**Comment by onury** [comment]
Thanks @4kochi.
Fixed this in v1.0.1

**Comment by 4kochi** [comment]
That was quick, thanks. I will test it.

**Comment by onury** [comment]
:) Let me know the results. Thanks.

**Comment by 4kochi** [comment]
Works fine :+1:

**Comment by onury** [comment]
excellent!

**Comment by testpossessed** [comment]
I have upgraded to 1.0.2 but I don't see the symbols in a Windows 8 console.  For example I see an uppercase V instead of the tick, is this what is expected?  Is there something else I need to do?

**Comment by 4kochi** [comment]
This is expected. The windows console does not support the tick, and the fallback is to render a symbol which looks like an uppercase V instead.

See https://github.com/sindresorhus/log-symbols/blob/master/index.js

**Comment by testpossessed** [comment]
Thanks for the clarification
