### ISSUE TITLE
Enable Terminal Reporter

### ISSUE THREAD

**Issue by fiznool** [onury/grunt-jasmine-nodejs#7]
The terminal reporter is useful, because it prints the results of the test suite as it is processed.

This means that if an unhandled exception occurs anywhere in my test suite, I can easily track it down, since the last test that is printed to the results is the test before the one that caused the error.

Using the default console reporter, it is impossible to tell where the error occurred!

Default console:

![screenshot from 2015-03-06 18 24 30](https://cloud.githubusercontent.com/assets/820863/6531101/5a1e9e60-c42e-11e4-926a-b08acac1622d.png)

Terminal reporter:

![screenshot from 2015-03-06 18 23 30](https://cloud.githubusercontent.com/assets/820863/6531105/5fbe962c-c42e-11e4-9637-b6caa1dfa562.png)

**Comment by fiznool** [comment]
Ok, the example isn't that great as the stack trace is pinpointing me to the line of code that is in error. However, sometimes a stack trace like this isn't available.

**Comment by onury** [comment]
I didn't enable the **terminal** reporter because it's similar to the default **console** reporter.

Did you try the **console** reporter with `verbose: true`? It outputs all the test suites and specs as a list. If there is a failure, they will be listed under **failed specs** with stack traces (regardless of the `verbose` option).

I don't see how it's impossible to see the error location. Can you show the rest of the output for console reporter?

**Comment by fiznool** [comment]
>  It outputs all the test suites and specs as a list. If there is a failure, they will be listed under failed specs with stack traces

The problem in this situation is that the spec runner encountered an uncaughtException, and thus the process was ended mid-run. This is why the verbose mode did not print anything out - the process died midway through, before the verbose bits could be logged out.

**Comment by onury** [comment]
I see. Ok, I'll enable the terminal reporter. 

I may also add a `progressive` option for console reporter for this kind of situation.

**Comment by fiznool** [comment]
> I may also add a progressive option for console reporter for this kind of situation.

That's cool, I'm in no rush for this (as I can just add the terminal reporter as a customReporter) so if you'd prefer to do that, no worries! :smile:

**Comment by onury** [comment]
Cool, I'll work on `progressive` option, if you're already using customReporter.

I'll close this issue when it's done.
Thanks

**Comment by onury** [comment]
This is fixed in the latest version 1.3.0
The new console reporter is progressive. Specs are output as they are executed. (Also see the `activity` option). Pls let me know if this works for you.

Also enabled terminal reporter for people used to it.
