### ISSUE TITLE
No specs found with grunt watch

### ISSUE THREAD

**Issue by LukeRiceApperson** [onury/grunt-jasmine-nodejs#8]
First off, thanks for making this, I've been using jasmine-node and grunt-jasmine-node and having 2.x out of the box is great and so far I really like it. 

I'm having an issue where when using my grunt watch task, specs are found the first time but not after changes. I searched through some of the dependencies in node_modules and found places where instance variables are used to check the number of specs to be run, potentially these are not reset after each iteration of running the tests. Any ideas? Thanks.

Here is my gruntfile:

```javascript
'use strict';

module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    jshint: {
      all: [
        'Gruntfile.js',
        'server.js',
        'tasks/**/*.js',
        'test/*.js',
        'backend/**/*.js'
      ],
      options: {
        jshintrc: '.jshintrc',
        jshintignore:'.jshintignore'
      },
    },

    jasmine_nodejs: {
      options: {
        specNameSuffix: "spec.js" // also accepts an array
      },
      backend: {
        specs:['backend/**']
      }
    },

    watch: {
      express: {
        options: {
          livereload: true,
          spawn: false
        },
        files: [
          'Gruntfile.js',
          'backend/**/*.js',
          'server.js'
        ],
        tasks: ['jshint', 'jasmine_nodejs:backend', 'express:defaults']
      }
    },

    express: {
      options: {
        script: './backend/server.js',
        port: 5000
      },
      defaults: {},
      stoppable: {}
    }
  });

  // Actually load this plugin's task(s).
  grunt.loadTasks('tasks');

  // These plugins provide necessary tasks.
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-jasmine-nodejs');

  // By default, lint and run all tests. Backend only so far.
  grunt.registerTask('default', ['jshint', 'jasmine_nodejs:backend']);

};
``` 

and here is my console output after changes to a spec file:
```
C:dsafdsafdsafdsa [Scaffolding-JasmineNode +1 ~5 -1 !]> grunt watch
Running "watch" task
Waiting...
>> File "backend\server.js" changed.

Running "jshint:all" (jshint) task
>> 5 files lint free.

Running "jasmine_nodejs:backend" (jasmine_nodejs) task
Executing specs...

.

Test Suites:

1) server

  √ should be a function


1 suite, 1 spec, 1 assert, 0 failures
Finished in 0.005 seconds

>> Successful!

Running "express:defaults" (express) task
Starting background Express server
server bound to port  5000

Running "watch" task
Completed in 0.245s at Tue Mar 10 2015 19:40:20 GMT-0400 (Eastern Daylight Time) - Waiting...
>> File "backend\server.spec.js" changed.

Running "jshint:all" (jshint) task
>> 5 files lint free.

Running "jasmine_nodejs:backend" (jasmine_nodejs) task
Executing specs...



Test Suites:
No specs found.
Finished in 0.001 seconds

>> Successful!

Running "express:defaults" (express) task
Stopping Express server
Starting background Express server
server bound to port  5000

Running "watch" task
Completed in 0.232s at Tue Mar 10 2015 19:40:31 GMT-0400 (Eastern Daylight Time) - Waiting...
```

**Comment by onury** [comment]
Hi @LukeRiceApperson. 

What happens when you run the specs directly, without the `watch` plugin?

I don't believe this is related to `jasmine_nodejs`. It might be your config or the [grunt-contrib-watch](https://github.com/gruntjs/grunt-contrib-watch) (which seems like unstable. I don't know the version you're using but it currently shows a build-failing badge).

**Comment by onury** [comment]
Also please run `grunt jasmine_nodejs --verbose` and see the spec files listed in the console output. Please check if they are correct.

**Comment by LukeRiceApperson** [comment]
Wow, thanks for the quick reply. Sorry if it turns out this has nothing to do with your work, but I've used this same gruntfile for grunt-jasmine-node earlier and simply swapped them out, so watch has been functioning unless there is some way its causing state to be stored or its doing some caching or something. 

I changed my default grunt task to this: 
```javascript 
  grunt.registerTask('default', ['jasmine_nodejs:backend', 'jasmine_nodejs:backend']);
```

and the output of a pain >grunt command is 

```
C:\dsfdsfadsa > grunt
Running "jasmine_nodejs:backend" (jasmine_nodejs) task
Executing specs...

.

Test Suites:

1) server

  √ should be a function


1 suite, 1 spec, 1 assert, 0 failures
Finished in 0.012 seconds

>> Successful!

Running "jasmine_nodejs:backend" (jasmine_nodejs) task
Executing specs...



Test Suites:
No specs found.
Finished in 0.004 seconds

>> Successful!

Done, without errors.
```

I would have thought at least that this would run the same configuration twice, but it seems to not matter? Do you have a sample of using any watch based grunt task that I could start with and work backwards?

Thanks again.

**Comment by onury** [comment]
No problem at all. 

This looks like a path problem since the result output indicates *no specs found*.

Your config seems strange to me. You have a `"test/"` directory but you've set `"backend/**"` for your specs in `jasmine_nodejs` configuration. Do you have any files with `spec.js` suffix in the `"backend/**"` directory?

**Comment by LukeRiceApperson** [comment]
Sorry for the confusion, I took the original gruntfile from a grunt-express-server example, which had a test folder. I removed it, but it wasn't doing anything and didn't change the output. The contents of backend are:

```
C:\dsfdsafdsa> ls backend

    Directory: C:\dsfdsafdsa\backend


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         3/10/2015   8:10 PM       1719 server.js
-a---         3/10/2015   7:40 PM        499 server.spec.js
```

That spec file is being run the first time in watch, or in the manually duplicated default task. I should have shown the output of --verbose before, but here it is, in case it helps either. 

```
C:\users\luke\Documents\Arduino\prototypeV1JSON\scaffolding [Scaffolding-JasmineNode +1 ~5 -1 !]> grunt jasmine_nodejs --verbose
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "tasks" tasks.
Loading "express.js" tasks...OK
+ express

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading C:\users\luke\Documents\Arduino\prototypeV1JSON\scaffolding\node_modules\grunt-contrib-jshint\package.json...OK
Parsing C:\users\luke\Documents\Arduino\prototypeV1JSON\scaffolding\node_modules\grunt-contrib-jshint\package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-contrib-watch" local Npm module tasks.
Reading C:\users\luke\Documents\Arduino\prototypeV1JSON\scaffolding\node_modules\grunt-contrib-watch\package.json...OK
Parsing C:\users\luke\Documents\Arduino\prototypeV1JSON\scaffolding\node_modules\grunt-contrib-watch\package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-jasmine-nodejs" local Npm module tasks.
Reading C:\users\luke\Documents\Arduino\prototypeV1JSON\scaffolding\node_modules\grunt-jasmine-nodejs\package.json...OK
Parsing C:\users\luke\Documents\Arduino\prototypeV1JSON\scaffolding\node_modules\grunt-jasmine-nodejs\package.json...OK
Loading "jasmine.task.js" tasks...OK
+ jasmine_nodejs
Loading "Gruntfile.js" tasks...OK
+ default

Running tasks: jasmine_nodejs

Running "jasmine_nodejs" task

Running "jasmine_nodejs:backend" (jasmine_nodejs) task
Verifying property jasmine_nodejs.backend exists in config...OK
File: [no files]
Options: specNameSuffix="spec.js", helperNameSuffix="helper.js", useHelpers=false, showColors, verboseReport, reporters={}, verbose
Enabled Reporters:
   Jasmine Console Reporter
Spec Files:
   [ 'C:\\users\\luke\\Documents\\Arduino\\prototypeV1JSON\\scaffolding\\backend\\server.spec.js' ]
Executing specs...

.

Test Suites:

1) server

  √ should be a function


1 suite, 1 spec, 1 assert, 0 failures
Finished in 0.014 seconds

>> Successful!

Done, without errors.
```

**Comment by onury** [comment]
Ok. I could reproduce this issue. The problem is the `spawn:false` option in `watch` task configuration. When I use this option I get the same problem as you do. First time, it runs but second and forth it won't.

Omitting the `spawn` option or setting it to `true` (as the default value) will let the task run normally.

There are lots of [issues related to `spawn`](https://github.com/gruntjs/grunt-contrib-watch/issues?q=is%3Aissue+is%3Aopen+spawn) in the grunt-contrib-watch repo. 

Let me know if it works for you when `spawn` option is omitted.

**Comment by onury** [comment]
Actually it is noted that `spawn:false` is prone to failure in grunt-contrib-watch docs:

[Why spawn as child processes as a default?](
https://github.com/gruntjs/grunt-contrib-watch/blob/master/docs/watch-examples.md#why-spawn-as-child-processes-as-a-default)

> The goal of this watch task is as files are changed, run tasks as if they were triggered by the user themself. Each time a user runs grunt a process is spawned and tasks are ran in succession. In an effort to keep the experience consistent and continually produce expected results, this watch task spawns tasks as child processes by default.

> Sandboxing task runs also allows this watch task to run more stable over long periods of time. As well as more efficiently with more complex tasks and file structures.

> Spawning does cause a performance hit (usually 500ms for most environments). It also cripples tasks that rely on the watch task to share the context with each subsequent run (i.e., reload tasks). If you would like a faster watch task or need to share the context please set the spawn option to false. Just be aware that with this option enabled, the watch task is more prone to failure.

**Comment by LukeRiceApperson** [comment]
Its working for me now too, thanks a lot!
